# 服务器配置
server:
  port: 8080  # 项目启动端口
# 数据库配置（适配Spring Boot3.x + MySQL8.0）
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
      # 注意：这里将原先的数据库名改成了 vetech_project
    url: jdbc:mysql://localhost:3306/vetech_project?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root  # 你的MySQL用户名
    password: Lhg20050831! # 你的MySQL密码

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.example.vetechspringboot.entity
  global-config:
    db-config:
      id-type: auto
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false


